version: '3.7'

services:
  db:
    container_name: "database"
    platform: linux/x86_64
    build:
      context: .
      dockerfile: db.Dockerfile
    networks:
      - default
    restart: always
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - "3306:3306"
    # setting some env vars to create the DB
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "wallet"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      # OR if you want to use "root" as the user, just these two lines
      # MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      # MYSQL_DATABASE: ${DATABASE_NAME}

    # we mount a data volume to make sure we don't lose data
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
  api:
    container_name:  "backend"
    # we want to use the image which is build from our Dockerfile
    build:
      context: .
      dockerfile: server.Dockerfile
    ports:
      - "8090:8090"
    # we are depending on the mysql backend
    depends_on:
      - db
    # We mount the working dir into the container, handy for development
    # This is what makes the hot reloading work inside of a Docker container
    volumes:
      - ./server:/app/
  client:
    container_name: client
    ports:
      - 5173:5173
    build:
      context: .
      dockerfile: client.Dockerfile
    depends_on:
      - api
    volumes:
      - ./client/:/client/
    command: yarn dev --host

networks:
  default:
volumes:
  mysql_data: